const TipoTransacaoEnum = {
    ENVIO_PROFESSOR: 'ENVIO_PROFESSOR',
    RECEBIMENTO_ALUNO: 'RECEBIMENTO_ALUNO',
    TROCA_VANTAGEM: 'TROCA_VANTAGEM',
    RECEBIMENTO_SEMESTRAL: 'RECEBIMENTO_SEMESTRAL'
};

module.exports = TipoTransacaoEnum;